import Head from 'next/head'
import Image from 'next/image'
import Intro from '../components/Intro'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import fav from '../public/favicon.ico';
import Services from '../components/Services'
import { data } from '../data'
import Testimonials from '../components/Testimonials'
export default function Home({services}) {
  console.log(services);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href={fav.src} />

      </Head>
      <Intro/>
      <Services services={services}/>
      <Testimonials/>
    </div>
  )
}

export const getStaticProps=async ()=>{
  const services= data;
  return{
    props:{
      services
    }
  }
}